//
//  PreferenceConstants.swift
//  NoMAD
//
//  Created by Tom Nook on 11/12/16.
//  Copyright © 2016 Trusource Labs. All rights reserved.
//

enum Preferences {
    static let aDDomain = "ADDomain"
    static let autoConfigure = "AutoConfigure"
    static let displayName = "DisplayName"
    static let expeditedLookup = "ExpeditedLookup"
    static let getHelpType = "GetHelpType"
    static let getHelpOptions = "GetHelpOptions"
    static let groups = "Groups"
    static let hidePrefs = "HidePrefs"
    static let kerberosRealm = "KerberosRealm"
    static let lastCertificateExpiration = "LastCertificateExpiration"
    static let loginComamnd = "LoginComamnd"
    static let loginItem = "LoginItem"
    static let lDAPServerList = "LDAPServerList"
    static let localPasswordSync = "LocalPasswordSync"
    static let lastUser = "LastUser"
    static let lastPasswordWarning = "LastPasswordWarning"
    static let passwordExpireAlertTime = "PasswordExpireAlertTime"
    static let renewTickets = "RenewTickets"
    static let showHome = "ShowHome"
    static let secondsToRenew = "SecondsToRenew"
    static let signInCommand = "SignInCommand"
    static let stateChangeAction = "StateChangeAction"
    static let template = "Template"
    static let userPrincipal = "UserPrincipal"
    static let userPasswordExpireDate = "UserPasswordExpireDate"
    static let userCommandTask1 = "UserCommandTask1"
    static let userCommandName1 = "UserCommandName1"
    static let userCommandHotKey1 = "UserCommandHotKey1"
    static let userPasswordSetDates = "UserPasswordSetDates"
    static let useKeychain = "UseKeychain"
    static let userAging = "UserAging"
    static let verbose = "Verbose"
    static let x509CA = "X509CA"
}

let ADDomain = "ADDomain"
let AutoConfigure = "AutoConfigure"
let DisplayName = "DisplayName"
let ExpeditedLookup = "ExpeditedLookup"
let GetHelpType = "GetHelpType"
let GetHelpOptions = "GetHelpOptions"
let Groups = "Groups"
let HidePrefs = "HidePrefs"
let KerberosRealm = "KerberosRealm"
let LastCertificateExpiration = "LastCertificateExpiration"
let LoginComamnd = "LoginComamnd"
let LoginItem = "LoginItem"
let LDAPServerList = "LDAPServerList"
let LocalPasswordSync = "LocalPasswordSync"
let LastUser = "LastUser"
let LastPasswordWarning = "LastPasswordWarning"
let PasswordExpireAlertTime = "PasswordExpireAlertTime"
let RenewTickets = "RenewTickets"
let ShowHome = "ShowHome"
let SecondsToRenew = "SecondsToRenew"
let SignInCommand = "SignInCommand"
let StateChangeAction = "StateChangeAction"
let Template = "Template"
let UserPrincipal = "UserPrincipal"
let UserPasswordExpireDate = "UserPasswordExpireDate"
let UserCommandTask1 = "UserCommandTask1"
let UserCommandName1 = "UserCommandName1"
let UserCommandHotKey1 = "UserCommandHotKey1"
let UserPasswordSetDates = "UserPasswordSetDates"
let UseKeychain = "UseKeychain"
let UserAging = "UserAging"
let Verbose = "Verbose"
let X509CA = "X509CA"
